version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/querys/init.sql:/docker-entrypoint-initdb.d/init.sql # Executa scripts SQL ao iniciar

volumes:
  pg_data:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_container
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: python3 etl.py
