#GET RAZÃO SOCIAL

GET https://etl-api.felipenonato.com:5000/operadoras?razao_social=18%20DE%20JULHO%20ADMINISTRADORA%20DE%20BENEF%C3%ADCIOS%20LTDA HTTP/1.1
Host: 69.62.100.190:5000
Accept: application/json